### ISSUE TITLE
Milstd2525 type enumeration is inaccurate

### ISSUE THREAD

**Issue by spyhunter99** [CMAPI/cmapi#71]
There is an enumeration for what "type" of object the symbol is, which according to 1.3, is either "lineString", or "point". That's a bit inaccurate since there are also areas, volumes, etc. It may be better to specify it as a "point" or "multipoint" to generalize it.

**Comment by briscoeej** [comment]
Because 2525 represents lines, areas, and tactical graphics like an ambush as a series of control points, we felt it simpler to divide the shape types as either a single point (icon) or a linestring of coordinates (lines, areas, specialized tactical graphics).  This follows the implementation of the Mission Command 2525 renderer at:

https://github.com/missioncommand/mil-sym-js
